
van:
  name: VanSunHo
  age: 29

spring:
  profiles:
    group:
      prod:
        - prod-info
  datasource:
    url: jdbc:postgresql://localhost:25432/kvp_springboot
    username: kvp-admin
    password: kvp-admin

server:
  port: 19998
